[package]
name = "app1"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "app1"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
serde.workspace = true
