[package]
name = "app2"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "app2"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
tokio.workspace = true
