[package]
name = "web-app"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
yew = { version = "0.22", features = ["csr"] }
yew-router = "0.19"
wasm-bindgen = "0.2"
web-sys = "0.3"
gloo = "0.11"
